databases:
  - name: bee_dice
    databaseName: bee_dice
    user: bee_dice

services:
  - type: web
    name: bee_dice
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bee_dice.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bee_dice
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
